# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('un', 'Unnecessary'), ('bt', 'Bought'), ('ah', 'Already Have')], max_length=2)),
                ('comments', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('online_order_links', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('priority', models.DecimalField(decimal_places=1, max_digits=2)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('needed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=100)),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('date_inactive', models.DateTimeField(blank=True, null=True)),
                ('date_complete', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('permenant', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TeamMember')),
            ],
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='belongs_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.Wishlist'),
        ),
        migrations.AddField(
            model_name='itemrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TeamMember'),
        ),
        migrations.AddField(
            model_name='itemrecord',
            name='is_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.ItemRequest'),
        ),
        migrations.AddField(
            model_name='itemrecord',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TeamMember'),
        ),
    ]
