# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 16:42
from __future__ import unicode_literals

from django.db import migrations

def create_team_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    User = apps.get_model('auth', 'User')
    Group.objects.create(name="cru | role | Student leader")
    Group.objects.create(name="cru | role | Staff member")

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_team_groups)
    ]
